services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Laravel-APP-1
    volumes:
      - ./app:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: webserver-laravel
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: db-laravel-app
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravelapp
      MYSQL_USER: Laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - laravel-network

volumes:
  db_data: {}

networks:
  laravel-network:
    driver: bridge
